---

language: "python"
python: "3.6"
before_install: "pip install poetry codecov"
install: "poetry install --verbose"
script:
  - "pytest --verbose --cov=couchutils tests"
  - "prospector couchutils"
  - "black --check couchutils"
  - "isort --recursive --check-only couchutils"
  - "codecov"
